export const CLASSES =
    {
           0: 'Almonds',
           1: 'Aluminum can',
           2: 'Apple juice',
           3: 'Apple juice 1 cup',
           4: 'Apple single',
           5: 'Apples',
           6: 'Apricots',
           7: 'Artichokes',
           8: 'Asparagus',
           9: 'Avocado',
           10: 'Bananas',
           11: 'Barley',
           12: 'Beef',
           13: 'Beer',
           14: 'Beer 1 glass',
           15: 'Beer gallon',
           16: 'Blackberries',
           17: 'Blueberries',
           18: 'Bread',
           19: 'Broccoli',
           20: 'Brussel sprouts',
           21: 'Butter',
           22: 'Cabbage',
           23: 'Canola oil',
           24: 'Car',
           25: 'Carrots',
           26: 'Cashews',
           27: 'Castor oil',
           28: 'Cauliflower',
           29: 'Celery',
           30: 'Cheese',
           31: 'Cheese slice',
           32: 'Cherries',
           33: 'Chestnuts',
           34: 'Chicken',
           35: 'Chickpeas',
           36: 'Chili peppers',
           37: 'Chocolate',
           38: 'Cigarette',
           39: 'Cocoa beans',
           40: 'Cocoa butter',
           41: 'Coconut',
           42: 'Cocunut oil',
           43: 'Coffee 1 cup',
           44: 'Coffee beans',
           45: 'Corn',
           46: 'Corn oil',
           47: 'Cotton T shirt',
           48: 'Cranberries',
           49: 'Cucumber',
           50: 'Currants',
           51: 'Dates',
           52: 'Diapers cloth',
           53: 'Diapers disposable',
           54: 'Egg',
           55: 'Egg dozen',
           56: 'Egg single',
           57: 'Eggplants',
           58: 'Figs',
           59: 'Fishing line',
           60: 'Foam cup',
           61: 'Garlic',
           62: 'Gin bottle',
           63: 'Gin one & half oz',
           64: 'Ginger',
           65: 'Glass bottle',
           66: 'Goat',
           67: 'Gooseberries',
           68: 'Grape juice',
           69: 'Grape juice 1 cup',
           70: 'Grapefruit',
           71: 'Grapefruit juice',
           72: 'Grapefruit juice 1 cup',
           73: 'Grapes',
           74: 'Greek yogurt',
           75: 'Green beans',
           76: 'Guavas',
           77: 'Hamburger',
           78: 'Hazelnuts',
           79: 'Icecream 1 scoop',
           80: 'Jeans',
           81: 'Juice box',
           82: 'Kale',
           83: 'Kiwi fruit',
           84: 'Lamb',
           85: 'Leather shoes',
           86: 'Lemons',
           87: 'Lentils',
           88: 'Lettuce',
           89: 'Limes',
           90: 'Loganberries',
           91: 'Mandarins',
           92: 'Mangoes',
           93: 'Milk',
           94: 'Milk 1 cup',
           95: 'Milk carton',
           96: 'Millet',
           97: 'Mulberries',
           98: 'Mustard seeds',
           99: 'Nectarines',
           100: 'Okra',
           101: 'Olive oil',
           102: 'Olives',
           103: 'Onions',
           104: 'Orange juice',
           105: 'Orange juice 1 cup',
           106: 'Oranges',
           107: 'Palm oil',
           108: 'Papayas',
           109: 'Paper coffee cup',
           110: 'Paper towel',
           111: 'Pasta',
           112: 'Peaches',
           113: 'Peanut oil',
           114: 'Peanuts',
           115: 'Pears',
           116: 'Peas',
           117: 'Pen',
           118: 'Peppers',
           119: 'Pet food dry',
           120: 'Pet food wet',
           121: 'Pineapple',
           122: 'Pineapple juice',
           123: 'Pineapple juice 1 cup',
           124: 'Pistachios',
           125: 'Pizza',
           126: 'Pizza slice',
           127: 'Plantains',
           128: 'Plastic bag',
           129: 'Plastic bottle',
           130: 'Plastic cup',
           131: 'Plastic holder',
           132: 'Plastic straw',
           133: 'Plums',
           134: 'Poppy seeds',
           135: 'Pork',
           136: 'Potato',
           137: 'Potato chips',
           138: 'Pumpkin',
           139: 'Rasberries',
           140: 'Rice',
           141: 'Rice brown',
           142: 'Rice flour',
           143: 'Rice white',
           144: 'Rolled oats',
           145: 'Rye',
           146: 'Rye flour',
           147: 'Safflower seeds',
           148: 'Salad',
           149: 'Sesame oil',
           150: 'Sesame seeds',
           151: 'Socks',
           152: 'Soda 500 mL',
           153: 'Sorghum',
           154: 'Soy beans',
           155: 'Soy sauce',
           156: 'Spinach',
           157: 'Squash',
           158: 'Strawberry',
           159: 'Suede shoes',
           160: 'Sugar cane',
           161: 'Sunflower seed oil',
           162: 'Sunflower seeds',
           163: 'Sweet potato',
           164: 'Tea',
           165: 'Tea 1 cup',
           166: 'Tin can',
           167: 'Tires',
           168: 'Toast',
           169: 'Tofu',
           170: 'Tomato',
           171: 'Tomato juice',
           172: 'Tomato juice 1 cup',
           173: 'Tomato ketchup',
           174: 'Toothbrush',
           175: 'Vanilla beans',
           176: 'Vodka bottle',
           177: 'Vodka one & half oz',
           178: 'Walnuts',
           179: 'Watermelon',
           180: 'Wheat flour',
           181: 'Whiskey bottle',
           182: 'Whiskey one & half oz',
           183: 'Wine 5 oz',
           184: 'Wine bottle',
           185: 'Wine gallon',
           186: 'Yogurt',
           187: 'Zucchini'
    };
