export const images = {
  meats: require('./images/Beef.png'),
  everyday_food: require('./images/hamburger.jpg'),
  seeds: require('./images/sunflower_seeds.png'),
  drinks_all: require('./images/coffee_small.png'),
  fruits: require('./images/apple.png'),
  everyday_items: require('./images/jeans.png'),
  grains: require('./images/rye.png'),
  alcoholic_drinks: require('./images/wine.png'),
  vegetables: require('./images/broccolli.png'),
  nuts_beans: require('./images/pistachios.png'),
  oils: require('./images/sesame_oil_small.png'),
  non_alcoholic_drinks: require('./images/milk.png'),
  water_drops: require('./images/water_drops.png'),
  landing_image: require('./images/LandingPage_Image_2x.png'),
  logo: require('./images/SiitchLogo_large.png'),
  // Navigation
  water_drop: require('./images/Navigation_Icons/WaterDrop_B&W.png'),
  water_drop_click: require('./images/Navigation_Icons/WaterDrop_BLUE.png'),
  grass: require('./images/Navigation_Icons/Earth_icon_B&W.png'),
  grass_select: require('./images/Navigation_Icons/earth_icon_green_3.png'),
  heart_select: require('./images/Navigation_Icons/Health_icon_pink.png'),
  heart: require('./images/Navigation_Icons/Health_icon_B&W.png'),
  recycle: require('./images/Navigation_Icons/Recycle_icon_B&W.png'),
  recycle_select: require('./images/Navigation_Icons/Recycle_icon_brown.png'),
};
